# Generated by Django 6.1.1 on 2026-09-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('description', models.CharField(max_length=250, verbose_name='Nombre del proyecto')),
                ('stack', models.JSONField(blank=True, default=list, help_text='Stack Tecnológico', verbose_name='Stack Tecnológico')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('type_project', models.CharField(choices=[('Trabajo', 'Work'), ('Personal', 'Personal')], default='Trabajo', max_length=10)),
            ],
        ),
    ]
