# Generated by Django 6.1.1 on 2026-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type_project',
            field=models.CharField(choices=[('Trabajo', 'Work'), ('Personal', 'Personal')], default='Trabajo', max_length=10, verbose_name='Tipo del proyecto'),
        ),
    ]
