# Generated by Django 6.1.1 on 2026-09-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='code_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código del proyecto'),
        ),
        migrations.AddField(
            model_name='projects',
            name='demo_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='URL del proyecto'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
    ]
