# Generated by Django 6.1.1 on 2026-09-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_code_url_projects_demo_url_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='projects',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='projects',
            name='team',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Equipo'),
        ),
    ]
