# Generated by Django 6.1.1 on 2026-09-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_platform_projects_role_projects_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Año'),
        ),
    ]
