# Generated by Django 6.1.1 on 2026-09-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='URL de la imagen'),
        ),
    ]
