# Generated by Django 6.1.1 on 2026-09-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=80, verbose_name='Empresa')),
                ('role', models.CharField(max_length=50, verbose_name='Rol')),
                ('initial_date', models.DateTimeField(max_length=80, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(max_length=80, verbose_name='Fin')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='Logros', verbose_name='Logros')),
                ('stack', models.JSONField(blank=True, default=list, help_text='Stack Tecnológico', verbose_name='Stack Tecnológico')),
            ],
        ),
    ]
