# Generated by Django 6.1.1 on 2026-09-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
